#sudo borders
##start the daemon
exec-once = ~/SDG-Hyprland-Additions/sudoborders/sudoborders-daemon.sh
##rule to color the windows with a red border if inactive, or a gradient red/pink border when active
windowrule = border_color rgba(AA222266) rgba(AA222266), match:tag elevated
windowrule = border_color rgba(f40fa5cc) rgba(AA2222CC) 100deg, match:tag elevated

