# sets the styling for the floating terminal called as menus
windowrule {
  name = floating-term-slim
  match:class = floating-term-slim
  center = on
  float = on
  size = 300 600
}

# sets opacity for menus
windowrule = opacity 0.85 0.85, match:class floating-term-slim
# ensure focus
windowrule = stay_focused on, match:class floating-term-slim

# menu borders
windowrule = border_color rgba(b8640099) rgba(b8640099), match:class floating-term-slim
windowrule = border_color rgba(ffcf00cc) rgba(b86400cc) 80deg, match:class floating-term-slim


## keybind
bind = $mainMod, X, exec, ~/SDG-Hyprland-Additions/hotkeymenu/menu.sh example.json
