# sets the styling for the floating terminal called as menu's
windowrule {
  name = quickrun
  match:class = quickrun
  center = on
  float = on
  size = 500 25
}
windowrule {
  name = tldr
  match:class = tldr
  center = on
  float = on
  size = 500 50
}

windowrule {
  name = floating-term
  match:class = floating-terminal
  center = on
  float = on
  size = 800 510
}
windowrule {
  name = floating-terminal-large
  match:class = floating-terminal-large
  center = on
  float = on
  size = 1200 900
}

# sets the styling for the floating terminal called as menu's
windowrule {
  name = floating-term-slim
  match:class = floating-term-slim
  center = on
  float = on
  size = 300 600
}

windowrule {
  name = runner
  match:class = runner
  move = 10 45
  float = on
  size = 400 900
}

# menu borders
windowrule = border_color rgba(b8640099) rgba(b8640099), match:class floating-term-slim
windowrule = border_color rgba(ffcf00cc) rgba(b86400cc) 80deg, match:class floating-term-slim

# quickrun borders
windowrule = border_color rgba(b8640099) rgba(b8640099), match:class quickrun
windowrule = border_color rgba(ffcf00cc) rgba(b86400cc) 80deg, match:class quickrun

# focused tag borders
windowrule = border_color rgba(b8640099) rgba(b8640099), match:tag focused
windowrule = border_color rgba(ffcf00cc) rgba(b86400cc) 80deg, match:tag focused


# sets opacity for menus
windowrule = opacity 0.85 0.85, match:class floating-term-slim

#prevents menu's from being unfocused if the mouse moves over another item
windowrule = stay_focused on, match:class floating-term-slim
windowrule = stay_focused on, match:class runner
windowrule = stay_focused on, match:class quickrun
windowrule = stay_focused on, match:tag focused
#dims the screen around the menu
windowrule = dim_around on, match:class floating-term-slim
windowrule = dim_around on, match:class quickrun


# keybinds menu bind
bind = $mainMod, k, exec, alacritty --class floating-terminal -e ~/SDG-Hyprland-Additions/additional-menus/keybinds.sh

# tldr menu bind
bind = $mainMod SHIFT, t, exec, alacritty --class tldr -e ~/SDG-Hyprland-Additions/additional-menus/tldr.sh

# quickrun menu bind
bind = $mainMod, r, exec, alacritty --class quickrun -e ~/SDG-Hyprland-Additions/additional-menus/quickrun.sh


