bind = $mainMod ALT, 1, exec, ~/SDG-Hyprland-Additions/layout/setlayout.sh 1 # use configuration 1
bind = $mainMod ALT, 2, exec, ~/SDG-Hyprland-Additions/layout/setlayout.sh 2 # use configuration 1
bind = $mainMod ALT, 3, exec, ~/SDG-Hyprland-Additions/layout/setlayout.sh 3 # use configuration 1
bind = $mainMod ALT, 4, exec, ~/SDG-Hyprland-Additions/layout/setlayout.sh 4 # use configuration 1
bind = $mainMod ALT, 5, exec, ~/SDG-Hyprland-Additions/layout/setlayout.sh 5 # use configuration 1
bind = $mainMod ALT, 6, exec, ~/SDG-Hyprland-Additions/layout/setlayout.sh 6 # use configuration 1
bind = $mainMod ALT, 7, exec, ~/SDG-Hyprland-Additions/layout/setlayout.sh 7 # use configuration 1
bind = $mainMod ALT, 8, exec, ~/SDG-Hyprland-Additions/layout/setlayout.sh 8 # use configuration 1
bind = $mainMod ALT, 9, exec, ~/SDG-Hyprland-Additions/layout/setlayout.sh 9 # use configuration 1
bind = $mainMod ALT, 0, exec, ~/SDG-Hyprland-Additions/layout/resetlayout.sh # switch back to dwindle
