# style specific wallpaper executable
exec-once = awww-daemon
exec-once = ~/ownCloud/ArchConfig/hyprscripts/wallpapers/wallpaper-daemon.sh ~/ownCloud/ArchConfig/styles/girlypop-dark/wallpaper-config/wallpaper.json



general {

    # configures the gaps between windows 
    gaps_in = 3
    # configures the gaps between windows and the outer edge of the screen
    gaps_out = 6
    # changes the border thiccness
    border_size = 3

    # set default border colors
    col.active_border = rgba(ca9ee6EE) rgba(ea999cEE) 90deg
    col.inactive_border = rgba(babbf1EE)
}

decoration {
    rounding = 15
    blur {
        # handles background blur for windows with transparency, higher size or higher passes gets different effects
        enabled = true
        size = 3
        passes = 2
    }
    shadow {
        # handles border shadows, can actually be used for glows too.
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1a99)
    }

    # set inactive windows to be slightly transparent
    inactive_opacity = 0.9

}

# floating borders
windowrule = border_color rgba(eebebeAA) rgba(eebebeAA), match:float 1
windowrule = border_color rgba(ca9ee6EE) rgba(eebebeEE) 45deg, match:float 1

# pinned borders
windowrule = border_color rgba(babbf1AA) rgba(babbf1AA), match:pin 1
windowrule = border_color rgba(99d1dbEE) rgba(babbf1EE) 124deg, match:pin 1

# proxmox borders
windowrule = border_color rgba(E16E00CC) rgba(E13E0099), match:initial_title ^Proxmox VE$
windowrule = border_color rgba(E17E00CC) rgba(E13E0099) rgba(E17E00CC) 139deg, match:initial_title ^Proxmox VE$

# menu borders
windowrule = border_color rgba(ca9ee699) rgba(ca9ee699), match:class floating-term-slim
windowrule = border_color rgba(ca9ee6EE) rgba(f4b8e4EE) 80deg, match:class floating-term-slim

# runner borders
windowrule = border_color rgba(ca9ee699) rgba(ca9ee699), match:class runner
windowrule = border_color rgba(ca9ee6EE) rgba(f4b8e4EE) 80deg, match:class runner

# quickrun borders
windowrule = border_color rgba(ca9ee699) rgba(ca9ee699), match:class quickrun
windowrule = border_color rgba(ca9ee6EE) rgba(f4b8e4EE) 80deg, match:class quickrun

# focused tag borders
windowrule = border_color rgba(ca9ee699) rgba(ca9ee699), match:tag focused
windowrule = border_color rgba(ca9ee6EE) rgba(f4b8e4EE) 80deg, match:tag focused

# sets opacity for menu's
windowrule = opacity 1 1, match:class floating-term-slim

# sudo borders
windowrule = border_color rgba(e7828466) rgba(e7828466), match:tag elevated
windowrule = border_color rgba(e64553FF) rgba(e78284CC) 100deg, match:tag elevated

# modals
windowrule = border_color rgba(e7828466) rgba(e7828466), match:modal 1
windowrule = border_color rgba(e64553FF) rgba(e78284CC) 100deg, match:modal 1

windowrule = opacity 1 1, match:content 3 