general {

    # configures the gaps between windows 
    gaps_in = 3
    # configures the gaps between windows and the outer edge of the screen
    gaps_out = 6
    # changes the border thiccness
    border_size = 3

    # set default border colors
    col.active_border = rgba(fefc9fFF) rgba(c8cdd1FF) 100deg
    col.inactive_border = rgba(441b2dFF)
}

# floating borders
#inactive
windowrule = border_color rgba(523221FF) rgba(523221FF), match:float 1
#active
windowrule = border_color rgba(523221FF) rgba(483c40FF) 90deg, match:float 1

# pinned borders
#inactive
windowrule = border_color rgba(523221FF) rgba(523221FF), match:pin 1
#active
windowrule = border_color rgba(523221FF) rgba(483c40FF) 90deg, match:pin 1

# proxmox borders
#inactive
windowrule = border_color rgba(523221FF) rgba(523221FF), match:initial_title ^Proxmox VE$
#active
windowrule = border_color rgba(523221FF) rgba(483c40FF) 90deg, match:initial_title ^Proxmox VE$

# menu borders
#inactive
windowrule = border_color rgba(6d5c55FF) rgba(6d5c55FF), match:class floating-term-slim
#active
windowrule = border_color rgba(b4bbc3FF) rgba(6d5c55FF) 80deg, match:class floating-term-slim

# runner borders
#inactive
windowrule = border_color rgba(6d5c55FF) rgba(6d5c55FF), match:class runner
#active
windowrule = border_color rgba(b4bbc3FF) rgba(6d5c55FF) 80deg, match:class runner

# quickrun borders
#inactive
windowrule = border_color rgba(6d5c55FF) rgba(6d5c55FF), match:class quickrun
#active
windowrule = border_color rgba(b4bbc3FF) rgba(6d5c55FF) 80deg, match:class quickrun

# focused tag borders
#inactive
windowrule = border_color rgba(6d5c55FF) rgba(6d5c55FF), match:tag focused
#active
windowrule = border_color rgba(b4bbc3FF) rgba(6d5c55FF) 80deg, match:tag focused

# sudo borders
#inactive
windowrule = border_color rgba(441b2dFF) rgba(441b2dFF), match:tag elevated
#active
windowrule = border_color rgba(e64553FF) rgba(e78284CC) 100deg, match:tag elevated

# modals
#inactive
windowrule = border_color rgba(441b2dFF) rgba(441b2dFF), match:modal 1
#active
windowrule = border_color rgba(e64553FF) rgba(e78284CC) 100deg, match:modal 1

