
# runner borders
windowrule = border_color rgba(b8640099) rgba(b8640099), match:class runner
windowrule = border_color rgba(ffcf00cc) rgba(b86400cc) 80deg, match:class runner
windowrule = stay_focused on, match:class runner

windowrule {
  name = runner
  match:class = runner
  move = 10 45
  float = on
  size = 400 900
}


bind = $mainMod, SPACE, exec, alacritty --class runner -e '~/SDG-Hyprland-Additions/fzfmenu/runner.sh apps'

