bind = $mainMod, PRINT, exec, ~/ownCloud/ArchConfig/hyprscripts/screenshots/region.sh # makes a region selection screenshot
bind = $mainMod SHIFT, PRINT, exec, ~/ownCloud/ArchConfig/hyprscripts/screenshots/window.sh # screenshots your active window
bind = CONTROL SHIFT, PRINT, exec, ~/ownCloud/ArchConfig/hyprscripts/screenshots/all-displays.sh # screenshots all displays and composes them into a single image
bind = $mainMod CONTROL, PRINT, exec, ~/ownCloud/ArchConfig/hyprscripts/screenshots/fullscreen.sh # screenshots your current monitor
bind = , PRINT,exec, ~/ownCloud/ArchConfig/hyprscripts/screenshots/mode-toggle.sh # toggles screenshots between clipboard-only, saving to file and opening in an editor. 

#sets satty, the screenshot editor, to be floating.
windowrule {
  name = satty
  match:initial_title = satty
  center = on
  float = on
  size = 1280 827
  opacity = 1 1
}