# style specific wallpaper executable
exec-once = awww-daemon
exec-once = ~/ownCloud/ArchConfig/hyprscripts/wallpapers/wallpaper-daemon.sh ~/ownCloud/ArchConfig/styles/retro/wallpaper-config/wallpaper.json

general {
    # set default border colors
    col.active_border = rgba(4AF626FF) rgba(4AF626FF) 90deg
    col.inactive_border = rgba(000000FF)
    # configures the gaps between windows 
    gaps_in = 4
    # configures the gaps between windows and the outer edge of the screen
    gaps_out = 8
}
decoration {
    rounding = 0
    blur {
        # handles background blur for windows with transparency, higher size or higher passes gets different effects
        enabled = false
        size = 3
        passes = 3
    }
    shadow {
        # handles border shadows, can actually be used for glows too.
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1a99)
    }
    # make modals dim the screen
    dim_modal = false
    dim_strength = 0.2

    # set inactive windows to be opaque
    inactive_opacity = 1

}
windowrule = opacity 1 1
animations {
    enabled = false
}

# runner borders
windowrule = border_color rgba(4AF626FF) rgba(000000FF), match:class runner
windowrule = border_color rgba(4AF626FF) rgba(4AF626FF) 80deg, match:class runner
windowrule = border_color rgba(4AF626FF) rgba(000000FF), match:class quickrun
windowrule = border_color rgba(4AF626FF) rgba(4AF626FF) 80deg, match:class quickrun
windowrule = border_color rgba(4AF626FF) rgba(000000FF), match:pin 1
windowrule = border_color rgba(4AF626FF) rgba(4AF626FF) 80deg, match:pin 1
windowrule = border_color rgba(4AF626FF) rgba(000000FF), match:float 1
windowrule = border_color rgba(4AF626FF) rgba(4AF626FF) 80deg, match:float 1
windowrule = opacity 1 1, match:initial_class Alacritty

windowrule = opacity 1 1, match:content 3 