general {

    # configures the gaps between windows 
    gaps_in = 3
    # configures the gaps between windows and the outer edge of the screen
    gaps_out = 6
    # changes the border thiccness
    border_size = 3

    # set default border colors
    col.active_border = rgba(929e5dFF) rgba(899457FF) 100deg
    col.inactive_border = rgba(414336FF)
}

# floating borders
#inactive
windowrule = border_color rgba(4f504eFF) rgba(4f504eFF), match:float 1
#active
windowrule = border_color rgba(4f504eFF) rgba(54546cFF) 90deg, match:float 1

# pinned borders
#inactive
windowrule = border_color rgba(4f504eFF) rgba(4f504eFF), match:pin 1
#active
windowrule = border_color rgba(4f504eFF) rgba(54546cFF) 90deg, match:pin 1

# proxmox borders
#inactive
windowrule = border_color rgba(4f504eFF) rgba(4f504eFF), match:initial_title ^Proxmox VE$
#active
windowrule = border_color rgba(4f504eFF) rgba(54546cFF) 90deg, match:initial_title ^Proxmox VE$

# menu borders
#inactive
windowrule = border_color rgba(535779FF) rgba(535779FF), match:class floating-term-slim
#active
windowrule = border_color rgba(646580FF) rgba(535779FF) 80deg, match:class floating-term-slim

# runner borders
#inactive
windowrule = border_color rgba(535779FF) rgba(535779FF), match:class runner
#active
windowrule = border_color rgba(646580FF) rgba(535779FF) 80deg, match:class runner

# quickrun borders
#inactive
windowrule = border_color rgba(535779FF) rgba(535779FF), match:class quickrun
#active
windowrule = border_color rgba(646580FF) rgba(535779FF) 80deg, match:class quickrun

# focused tag borders
#inactive
windowrule = border_color rgba(535779FF) rgba(535779FF), match:tag focused
#active
windowrule = border_color rgba(646580FF) rgba(535779FF) 80deg, match:tag focused

# sudo borders
#inactive
windowrule = border_color rgba(414336FF) rgba(414336FF), match:tag elevated
#active
windowrule = border_color rgba(e64553FF) rgba(e78284CC) 100deg, match:tag elevated

# modals
#inactive
windowrule = border_color rgba(414336FF) rgba(414336FF), match:modal 1
#active
windowrule = border_color rgba(e64553FF) rgba(e78284CC) 100deg, match:modal 1

