# style specific wallpaper executable
exec-once = awww-daemon
exec-once = ~/ownCloud/ArchConfig/hyprscripts/wallpapers/wallpaper-daemon.sh ~/ownCloud/ArchConfig/styles/anime-girl/wallpaper-config/wallpaper.json

source = ~/ownCloud/ArchConfig/styles/anime-girl/hyprland/colors.conf



decoration {
    blur {
        enabled = false
        size = 1
        passes = 4
    }
}